### ISSUE TITLE
Error when decompressing in readData

### ISSUE THREAD

**Issue by Maaniksharma** [Tonel/nodejs-redis-demo#1]
I got this error when i tried to decompress the data 
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at processChunkSync (node:zlib:457:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.syncBufferWrapper [as inflateSync] (node:zlib:809:14)
    at readData (/home/maanik/Documents/redis/firstRedisLayer/src/middlewares/redis.js:72:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/maanik/Documents/redis/firstRedisLayer/src/middlewares/redis.js:92:27 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

**Comment by Maaniksharma** [comment]
I simply flushed the stored data in redis server .Client is taking the previous uncompressed data and trying to decompress it
